# Tarea 1 - Estadística Computacional

- Nombre: Valentina Alejandra Bastidas Schade
- Nombre: Diana Marcela Martínez Ruiz

Curso: Estadística Computacional

Doctorado en Estadística


Responda las preguntas que se indican colocando el código requerido. El Notebook se entrega totalmente ejecutado.

**Ingrese los Toolbox que se utilizarán en este Jupyter**

In [53]:
import numpy as np #se trabaja con listas


## 1. Indicadores estadísticos.

En estadística, en muchas ocasiones se requiere implementar indicadores o estadísticos. En esta pregunta deberá implementar los siguientes indicadores:

1. **Symmetric mean absolute percentage error (SMAPE or sMAPE)**: es una medida de precisión basada en errores porcentuales (o relativos).

$$sMAPE = \frac{100\%}{n}\sum_{t=1}^n \frac{|F_t-A_t|}{(|A_t|+|F_t|)/2}$$

donde $A_t$ es el valor real y $F_t$ es el valor de pronóstico.

Implementar la Función sMAPE:

In [54]:
def SMAPE(d,p):
  res=[]
  for i in range(0,20):
    res.append(abs(d[i]-p[i])/((abs(d[i])+abs(p[i]))/2))
  SMAPE=(100/len(d))*sum(res)
  print(SMAPE)

Aplicar la función sMAPE de las siguientes listas:

Dato = { 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 }
       
Predicción = { 3.58,  4.3 ,  0.5 , -3.11, -1.94,  3.71,  1.56, -1.55, -2.77,
       -0.51,  2.93,  2.14, -1.76, -1.96, -0.51,  2.96, -0.34, -3.33,
       -3.49,  1.5}


In [55]:
Dato = [ 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 ]
       
Prediccion = [ 3.58,  4.3 ,  0.5 , -3.11, -1.94,  3.71,  1.56, -1.55, -2.77,
       -0.51,  2.93,  2.14, -1.76, -1.96, -0.51,  2.96, -0.34, -3.33,
       -3.49,  1.5]

In [56]:
res=SMAPE(Dato, Prediccion)

53.15507816129964


2. **Coeficiente de correlación de Spearman ($\rho$)**: es una medida de la correlación (la asociación o interdependencia) entre dos variables aleatorias (tanto continuas como discretas). Para calcular $\rho$, los datos son ordenados y reemplazados por su respectivo orden.

El estadístico está dado por:

$$\rho = 1 - \frac{6\sum_i D_{(i)}^2}{N(N^2-1)}$$

donde $D_{(i)}$ es la diferencia entre los correspondientes estadísticos de orden de $x$ e $y$. $N$ es el número de parejas de datos.


Calcular el coeficiente de correlación de Spearman para los siguientes datos:
    
Dato = { 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 }
       
Predicción = { 3.58,  4.3 ,  0.5 , -3.11, -1.94,  3.71,  1.56, -1.55, -2.77,
       -0.51,  2.93,  2.14, -1.76, -1.96, -0.51,  2.96, -0.34, -3.33,
       -3.49,  1.5}

In [57]:
Dato = [ 1.5 , 2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5]
       
Prediccion = [ 3.58,  4.3 ,  0.5 , -3.11, -1.94,  3.71,  1.56, -1.55, -2.77,
       -0.51,  2.93,  2.14, -1.76, -1.96, -0.51,  2.96, -0.34, -3.33,
       -3.49,  1.5]

In [58]:
def Spearman(Dato,Prediccion):
  Dato2=sorted(Dato.copy()) #esta función genera los índices de la variable dato
  indice=[]
  for i in range(len(Dato)):
    indice.append(Dato2.index(Dato[i]))
  

  Prediccion2=sorted(Prediccion.copy())#esta función genera los índices de la variable prediccion
  indice2=[]
  for i in range(len(Prediccion)):
    indice2.append(Prediccion2.index(Prediccion[i]))
  

  def twice(a): #esta funcion reemplaza los valores de los índices repetidos por el promedio de ellos
    for i in range(len(a)):
      for j in range(i+1,len(a)):
        if a[i]==a[j]: 
          a[i]=(a[i]*2+1)/2
          a[j]=a[i]
    return(a)
  
  indice=twice(indice)
  indice2=twice(indice2)
  
  d2=[]
  for i in range(len(Dato)):
    d2.append((indice[i]-indice2[i])**2)
  #return(d)

  coef=1-(6*(sum(d2))/(len(Dato)*(len(Dato)**2 -1)))
  print(coef)


Spearman(Dato,Prediccion)

0.9278195488721804


3. **Coeficiente de Gini:** es una medida de la desigualdad. El coeficiente de Gini es un número entre 0 y 1, en donde 0 se corresponde con la perfecta igualdad (todos tienen los mismos ingresos) y donde el valor 1 se corresponde con la perfecta desigualdad. Para obtener el coeficiente de Gini, en general se utiliza la fórmila de Brown:

$$G = \left|1 - \sum_{k=1}^n (X_{k+1}-X_k)(Y_{k+1}+Y_k)\right|$$

donde $X$ e $Y$ corresponden a la proporción acumulada de las variables.

Implementar la función que calcule el coeficiente de Gini.


Obtener el coeficiente de Gini para las siguientes dos proporciones:

| Variables Acumuladas| Clase 1 | Clase 2 | Clase 3 | Clase 4 | Clase 5 |
| --- | --- | --- | --- | --- | --- |
| X | 0.09 | 0.33 | 0.45 | 0.78 | 1 |
| Y | 0.17 | 0.48 | 0.62 | 0.86 | 1 |



In [59]:
X=[0.09,0.33,0.45,0.78,1]
Y=[0.17,0.48,0.62,0.86,1]

In [60]:
def gini(x,y):
  prod=[]
  for i in range(len(X)-1): 
    prod.append((X[i+1]-X[i])*(Y[i+1]+Y[i]))
  gini=abs(1-sum(prod))
  return(gini)

print(gini(X,Y))

0.1856


## 2. Algoritmos

1. Dado dos conjuntos de datos ordenados y de tamaños diferentes, realizar una función que mezcle ambos conjunto y genere un nuevo conjunto con todos los datos ordenados.

In [61]:
def ordenada(d1,d2):
  d=d1+d2
  for i in range(len(d)):
      minimo_d=i
      for j in range (i+1,len(d)):
        if d[minimo_d]>d[j]:
          minimo_d=j
        #intercambiar el elemento más pequeño
      d[i],d[minimo_d]=d[minimo_d],d[i]
  return(d) 

Aplicar el algoritmo para mezclar y ordenar los siguientes conjuntos:

$$D_1 = \{5, 7, 15, 23, 45, 72, 83\}$$

$$D_2= \{1, 2, 6, 29, 37, 75, 100, 110, 115, 117\}$$

In [62]:
D1=[5,7,15,23,45,72,83]
D2=[1,2,6,29,37,75,100,110,115,117]

In [63]:
print(ordenada(D1,D2))
type(ordenada(D1,D2))

[1, 2, 5, 6, 7, 15, 23, 29, 37, 45, 72, 75, 83, 100, 110, 115, 117]


list

2. La equivalencia de los símbolos básicos de los números romanos es la siguiente:

|Número Romano | I | V | X | L | C | D | M |
| --- | --- | --- | --- | --- | --- | --- | --- |
|Número decimal| 1 | 5 | 10 | 50 | 100 | 500 | 1000 |

Los enteros romanos se escriben de acuerdo a las siguientes reglas:

- Si una letra está seguida inmediatamente por una de igual o menor valor, su valor se suma al total acumulado. Así, XX = 20, XV = 15 y VI = 6.
- Si una letra está seguida inmediatamente por una de mayor valor, su valor se sustrae del total acumulado. Así, IV = 4, XL = 40 y CM = 900.

Escriba la función que reciba un string con un número en notación romana, y entregue el entero equivalente:

In [64]:
x=input('Ingrese un número romano: ')
def romano(x):
    d={"I":1,"V":5,"X":10,"L":50,"C":100,"D":500,"M":1000}
    acum=0
    for i in range(0,len(x)):
        if i==0 or d[x[i]]<=d[x[i-1]]:
            acum+=d[x[i]]
        else:
            acum+=d[x[i]]-2*d[x[i-1]]
    return(acum)
 
print('El número arábigo correspondiente es: ', romano(x))

Ingrese un número romano: CMXLIX
El número arábigo correspondiente es:  949


## 3. Algoritmos en Series de Tiempo

Una serie de tiempo es una secuencia de valores numéricos obtenidos a intervalos de tiempos regulares.

$$X=\{x_1, x_2,....., x_t, ..., x_T\}$$

1. Las medias móviles con retardo $p$ de una serie de tiempo son las secuencia de todos los promedios de $p$ valores consecutivos de la serie. Realizar una función que retorne el arreglo de las medias móviles con retardo $p$ de la serie.

In [65]:
def med_movil(x,p):
  mm=[]
  for i in range(len(x)-(p-1)):
    mm.append(np.mean(Dato[i:(i+p)]))
  return(mm)

Aplicar la función a los siguientes datos:

Dato = { 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 }

In [66]:
Dato = [1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 ]
print(len(Dato))

20


In [68]:
#retardo p=10 (ejemplo)
a=med_movil(Dato,10)
print(a)
print(len(a))

[0.03200000000000004, 0.15999999999999998, 0.04899999999999995, -0.13400000000000004, -0.11200000000000003, 0.08099999999999999, 0.15499999999999997, -0.002000000000000035, -0.15300000000000008, -0.07000000000000002, 0.12099999999999995]
11


2. Las diferencias finitas de una serie de tiempo son la secuencia de todas las diferencias entre un valor y el anterior. Escribir una función que retorne el arreglo de las diferencias finitas de la serie.

In [69]:
def dife_fini(d):
  diferencia_finita=[] 
  t=0
  for i in range(1,len(d)):
    t=d[i]-d[i-1]
    diferencia_finita.append(t)
  return(diferencia_finita)

Aplicar la función a los siguientes datos:

Dato = { 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 }

In [70]:
a=dife_fini(Dato)
print(a)
print(len(a))

[1.3900000000000001, -2.97, -2.85, 1.58, 3.61, 0.2100000000000004, -3.5200000000000005, -1.93, 2.57, 3.19, -0.9999999999999998, -3.69, -0.8, 3.29, 2.42, -2.1, -3.46, 0.41000000000000014, 3.65]
19


3. En algunos métodos se requiere construir la matriz de rezagos de orden p. Esto es, dado la serie de tiempo:

$$X=\{x_1, x_2,....., x_t, ..., x_T\}$$

La matriz de rezagos de orden $p$ está dada por:

$$M = \left[\begin{array}{cccccc}
x_1 & x_2 & ... & x_p\\
x_2 & x_3 & ... & x_{p+1}\\
x_4 & x_5 & ... & x_{p+2}\\
... & ... & ... & ...\\
x_{T-p} & x_{T-p+1} & ... & x_{T-1}\\
x_{T-p+1} & x_{T-p+2} & ... & x_{T}\\
\end{array}
\right]$$ 

Realizar una función que construya dicha estructura de datos.

Aplicar la función a los siguientes datos:

Dato = { 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 }

In [72]:
#Data= [1,2,3,4,5,6,7,8,9] #quedarían finalmente 3-(n+1) elementos por columna?
def rezagos(x,p):
  M=[]
  for i in range(len(x)-(p-1)):
    M=M+x[i:i+p]
    R=np.array(M)
  F=R.reshape((len(x)-(p-1)),p)
  return(F)

#ejemplo para p=9
print(rezagos(Dato,9))
type(rezagos(Dato,9))

[[ 1.5   2.89 -0.08 -2.93 -1.35  2.26  2.47 -1.05 -2.98]
 [ 2.89 -0.08 -2.93 -1.35  2.26  2.47 -1.05 -2.98 -0.41]
 [-0.08 -2.93 -1.35  2.26  2.47 -1.05 -2.98 -0.41  2.78]
 [-2.93 -1.35  2.26  2.47 -1.05 -2.98 -0.41  2.78  1.78]
 [-1.35  2.26  2.47 -1.05 -2.98 -0.41  2.78  1.78 -1.91]
 [ 2.26  2.47 -1.05 -2.98 -0.41  2.78  1.78 -1.91 -2.71]
 [ 2.47 -1.05 -2.98 -0.41  2.78  1.78 -1.91 -2.71  0.58]
 [-1.05 -2.98 -0.41  2.78  1.78 -1.91 -2.71  0.58  3.  ]
 [-2.98 -0.41  2.78  1.78 -1.91 -2.71  0.58  3.    0.9 ]
 [-0.41  2.78  1.78 -1.91 -2.71  0.58  3.    0.9  -2.56]
 [ 2.78  1.78 -1.91 -2.71  0.58  3.    0.9  -2.56 -2.15]
 [ 1.78 -1.91 -2.71  0.58  3.    0.9  -2.56 -2.15  1.5 ]]


numpy.ndarray